import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    guides: [{type: 'autogenerated', dirName: 'guides'}],
    reference: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
